# https://docs.docker.com/compose/

# Compose is a tool for defining and running
# multi-container Docker applications. With Compose,
# you use a YAML file to configure your application’s
# services. Then, with a single command, you create
# and start all the services from your configuration.

version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    networks: 
      - overlay
  redis:
    image: "redis:alpine"
    networks: 
      - overlay
networks:
  overlay:
